{"uuid": "101854c6-8fd5-4d3b-b835-b32d80ca8e69", "children": ["44faf0cd-3d11-4c0a-b2a9-52a48a8abfab"], "befores": [{"name": "login_fixtrue", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message: \n\n", "trace": "  File \"D:\\python\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"D:\\python\\lib\\site-packages\\_pytest\\fixtures.py\", line 1111, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"D:\\python\\lib\\site-packages\\_pytest\\fixtures.py\", line 917, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"F:\\pytestUI\\case\\conftest.py\", line 26, in login_fixtrue\n    web.login()\n  File \"F:\\pytestUI\\pages\\login_page.py\", line 36, in login\n    self.input_username(user)\n  File \"F:\\pytestUI\\pages\\login_page.py\", line 23, in input_username\n    self.input(self.loc1, text)\n  File \"F:\\pytestUI\\common\\base.py\", line 71, in input\n    ele = self.find(locator)\n  File \"F:\\pytestUI\\common\\base.py\", line 52, in find\n    raise msg\n  File \"F:\\pytestUI\\common\\base.py\", line 49, in find\n    ele = WebDriverWait(self.driver, self.timeout, self.t).until(EC.presence_of_element_located(locator))\n  File \"D:\\python\\lib\\site-packages\\selenium\\webdriver\\support\\wait.py\", line 80, in until\n    raise TimeoutException(message, screen, stacktrace)\n"}, "start": 1607929168921, "stop": 1607929183686}], "start": 1607929168921, "stop": 1607929183707}